### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by wjr-wjr** [zstar1003/yolov5_pyqt5#1]
请问作者对于6.0以上的版本有做图像检测和摄像头检测的功能的想法吗

**Comment by zstar1003** [comment]
这个并不难，视频检测和摄像头检测只需把每一帧的检测结果替换到目前的label中即可。
之后有空会考虑添加该功能。

**Comment by wjr-wjr** [comment]
嗯嗯，感谢作者的意见，对于新手来说很有帮助
