### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by wjr-wjr** [zstar1003/yolov5_pyqt5#2]
作者您好，我今天试了一下将视频和摄像头获取的图片截取出每一帧，并将每一帧图片作为要检测的图像。按照你所给的代码框架，我设计的是将每一帧图片保存在一个文件夹下，然后如图片检测那样给出每一帧图片路径，最后再把检测结果显示于label中，对于帧的截取是通过设置定时器30ms截取一次，但是这样检测出来的视频和摄像头感觉实时性不足，有一定的延迟。而我看5.0版本作者您是直接对截取图片进行检测和显示，并没有先把图片保存->检测->显示这样的流程，我想请问在你所给出的6.0版本中，有没有什么办法像5.0版本那样能加快检测效率的方法呢。
![image](https://user-images.githubusercontent.com/76729954/233968323-713ec302-e889-4b39-bf27-b36d27000c01.png)

**Comment by zstar1003** [comment]
io读取效率不满足实时显示的需要，实际上，在detect的输出中，包含了每一帧的numpy信息，可以直接从内存中读取该信息进行转换。目前已更新了一个版本，支持了视频检测的需求。
代码较乱，后续有时间会再进行整理。
