### ISSUE TITLE
通过tensorrt导出engine文件后无法使用

### ISSUE THREAD

**Issue by Xana2015** [zstar1003/yolov5_pyqt5#5]
作者您好，很感谢你可以分享这份代码，我有一点问题想要请教一下
在正常pt文件使用没有问题，但我想使用加速过的模型，main.py我将line185的"Model files(*.pt)"改为"Model files(*.engine)"，而当我使用tensorrt导出的engine文件后会出现闪退的问题。
请问这个问题该如何解决。

**Comment by zstar1003** [comment]
请提供具体报错信息。如果使用pycharm

**Comment by zstar1003** [comment]
请提供具体报错信息。如果使用pycharm

**Comment by zstar1003** [comment]
请提供具体报错信息。
闪退问题，如果使用pycharm编辑器，可以勾选emulate terminal in ouput console，查看具体报错内容

**Comment by Xana2015** [comment]
查看具体报错内容后已经解决了问题，再次感谢你可以分享这份代码，对我帮助很大。
